name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to release, for example "v2.1" tag'
        required: true

jobs:
  release-gerber-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Export corne-cherry gerber
      uses: nerdyscout/kicad-exports@master
      with:
        cmd: fabrication
        dir: corne-cherry/gerber
        board: corne-cherry/pcb/corne-cherry.kicad_pcb
        schematic: corne-cherry/pcb/corne-cherry.sch
    - name: Export corne-chocolate gerber
      uses: nerdyscout/kicad-exports@master
      with:
        cmd: fabrication
        dir: corne-chocolate/gerber
        board: corne-chocolate/pcb/corne-chocolate.kicad_pcb
        schematic: corne-chocolate/pcb/corne-chocolate.sch
    - name: Export corne-classic gerber
      uses: nerdyscout/kicad-exports@master
      with:
        cmd: fabrication
        dir: corne-classic/gerber
        board: corne-classic/pcb/corne-classic.kicad_pcb
        schematic: corne-classic/pcb/corne-classic.sch
    - name: Export corne-light gerber
      uses: nerdyscout/kicad-exports@master
      with:
        cmd: fabrication
        dir: corne-light/gerber
        board: corne-light/pcb/corne-light.kicad_pcb
        schematic: corne-light/pcb/corne-light.sch

    - name: Zip Gerber files
      run: |
          zip -r --junk-paths corne-cherry-gerber.zip corne-cherry/gerber
          zip -r --junk-paths corne-chocolate-gerber.zip corne-chocolate/gerber
          zip -r --junk-paths corne-light-gerber.zip corne-light/gerber
          zip -r --junk-paths corne-classic-gerber.zip corne-classic/gerber

    - name: Release to GiHub
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.ref }}
        files: "*.zip"
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
